Predict the price of the Uber ride from a given pickup point to the agreed drop-off
location using linear regression model.
A) Pre-process the dataset.
B) Check the correlation
C) Evaluate the models and compare their respective scores like R2, RMSE, etc.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('E:\\dataset\\uber.csv')

In [ ]:
df

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance
0,8.5,2014-01-01,-73.995383,40.720680,-73.995978,40.736200,2,0.015531
1,26.0,2014-01-01,-73.976075,40.759432,-74.007680,40.740772,6,0.036702
2,22.5,2014-01-01,-73.982268,40.745457,-74.004782,40.706950,1,0.044606
3,5.5,2014-01-01,-73.970427,40.752365,-73.981125,40.747937,2,0.011578
4,17.0,2014-01-01,-73.945873,40.801373,-73.973143,40.743863,1,0.063648
...,...,...,...,...,...,...,...,...
2125,8.5,2014-01-31,-73.967885,40.763388,-73.955567,40.783161,1,0.023296
2126,14.0,2014-01-31,-73.962542,40.772987,-73.977230,40.758917,6,0.020340
2127,8.0,2014-01-31,-73.982534,40.756929,-73.987059,40.760832,1,0.005976
2128,6.0,2014-01-31,-73.982652,40.745070,-73.973608,40.751503,1,0.011099
2129,15.0,2014-01-31,-74.006410,40.743883,-73.987823,40.756271,2,0.022337

In [ ]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,distance
count,2130.000000,2130.000000,2130.000000,2130.000000,2130.000000,2130.000000,2130.000000
mean,10.468826,-73.979421,40.751971,-73.977264,40.751333,1.712207,0.027154
std,5.379518,0.022166,0.023335,0.023889,0.027058,1.366681,0.019805
min,4.500000,-74.017175,40.643685,-74.017943,40.635132,1.000000,0.004845
25%,6.500000,-73.992403,40.736719,-73.991666,40.735144,1.000000,0.013071
50%,9.000000,-73.982194,40.753216,-73.980723,40.752414,1.000000,0.020994
75%,12.500000,-73.969100,40.767158,-73.966678,40.767998,2.000000,0.034750
max,33.830000,-73.776688,40.849642,-73.736412,40.866837,6.000000,0.114940

In [ ]:
corr = df.corr()
corr.style.background_gradient(cmap = "BuGn")

In [ ]:
x = df['distance'].values.reshape(-1, 1)
y = df['fare_amount'].values.reshape(-1, 1)

In [ ]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
x_std = std.fit_transform(x)
y_std = std.fit_transform(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_std, y_std, test_size = 0.2, random_state = 0)

In [ ]:
from sklearn.linear_model import LinearRegression
l_reg = LinearRegression()
l_reg.fit(x_train, y_train)
train_score = l_reg.score(x_train, y_train)
test_score = l_reg.score(x_test, y_test)
print("Training set score: ", train_score)
print("Testing set score: ", test_score)

Training set score:  0.7601509717811463
Testing set score:  0.7742213292101866

In [ ]:
y_pred = l_reg.predict(x_test)
df = {"Actual": y_test, "Predicted": y_pred}

In [ ]:
from sklearn import metrics

print("r2 score: ", metrics.r2_score(y_test, y_pred))
print("Mean sqared error: ", metrics.mean_squared_error(y_test, y_pred))
print("Mean absolute error: ", metrics.mean_absolute_error(y_test, y_pred))
print("Root mean squared error: ", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

r2 score:  0.7742213292101866
Mean sqared error:  0.21328011425528853
Mean absolute error:  0.33428235687706626
Root mean squared error:  0.4618226004163163

In [ ]:
from tabulate import tabulate
print(tabulate(df, headers = "keys", tablefmt = 'pspl'))

     Actual     Predicted
-----------  ------------
 1.02843     -0.184749
-0.366072    -0.379188
-0.830906    -0.469004
 0.470631     0.45027
-0.923873    -0.867893
-0.552005    -0.608699
 0.377664     0.317061
-1.10981     -0.8609
-1.10981     -0.766916
-0.923873    -0.856356
-0.180138    -0.736829
-0.552005    -0.0609121
 0.470631     0.801232
-0.273105     0.131945
 1.02843      0.0469107
-0.366072    -0.293227
-1.01684     -0.863122
-0.366072    -0.16557
-0.366072    -0.0529477
-0.366072    -0.27436
 3.16667      3.29898
-1.01684     -0.737457
-0.830906    -0.65613
-1.10981     -0.780289
 1.02843      1.04228
-0.0871707   -0.0643691
-0.0871707   -0.275547
 0.470631     0.75573
 0.842499     1.11876
 0.842499    -0.101376
 1.4003       1.07681
-0.830906    -0.592355
-1.01684     -0.624765
-0.459039    -0.260432
 0.935466     1.04136
 0.0987632   -0.269977
-0.366072    -0.561207
-0.273105     0.0562603
-0.923873    -0.701588
 0.470631     1.24389
-0.0871707    0.322372
 0.656565     0.6175
 0.00579625  -0.664722
 0.00579625   0.853725
-0.830906    -0.739581
 1.6792       0.782027
 2.5159       1.70794
 2.32997      1.81048
-0.0871707   -0.201231
-1.10981     -0.856347
-0.459039    -0.254434
-0.737939    -0.493554
-0.459039    -0.257551
 1.49327      1.63857
-0.737939    -0.591498
 0.656565    -0.702519
 0.0987632   -0.252429
 0.0987632    0.130474
 0.19173      0.141496
 0.00579625  -0.211119
 2.32997      3.4181
-0.830906    -0.539408
 0.284697     0.505939
 3.72447      3.28916
 2.05107      2.21079
 1.86514      1.74926
-0.737939    -0.487297
 1.30733      1.16462
-0.366072    -0.152132
-0.459039    -0.615288
-1.01684     -0.954811
-0.273105    -0.261449
 1.58623      0.909441
 0.00579625   0.0236133
 0.377664     0.735422
-0.273105     0.0973373
 0.00579625  -0.402748
-0.366072     0.154632
-0.830906    -0.547617
-0.830906    -0.606036
-0.644972    -0.531722
-0.273105     0.0622929
-1.10981     -0.762176
-0.923873    -0.579837
-0.459039    -0.401182
-0.459039    -0.74132
-0.180138     2.44323
-0.644972    -0.261429
 0.00579625   0.272455
-0.459039    -0.76215
 0.749532     1.08267
 1.1214       1.73841
-1.10981     -0.737735
-0.0871707   -0.0297877
-0.552005    -0.715872
-0.459039     0.23151
 0.00579625  -0.380317
-1.01684     -0.940199
-0.273105     0.0943755
-0.459039    -0.368315
 0.842499     0.822675
-0.180138     0.170221
-0.737939    -0.66941
-0.737939    -0.827354
-0.552005    -0.232442
-0.273105    -0.404747
 1.58623      1.77716
-0.830906    -0.765316
-0.180138    -0.0353731
 1.30733      0.624796
 0.284697     0.154878
-0.459039    -0.530254
 1.30733      0.322321
 0.935466     0.155944
-0.552005    -0.504878
-0.737939    -0.847406
 0.00579625  -0.160843
-0.0871707   -0.169792
-0.273105    -0.253375
-0.552005    -0.752275
 1.58623      1.29927
-0.273105     0.0190324
-0.180138     0.152494
-0.737939    -0.567959
-0.552005     0.0162948
 1.1214       1.10856
-0.830906    -0.461599
 1.1214       1.75116
-1.01684     -0.848696
 1.77217      0.900139
-0.0871707   -0.160719
-1.01684     -0.601294
-0.737939    -0.645692
 2.05107      0.811508
 1.6792       1.53759
-0.273105    -0.337199
-0.273105    -0.229042
 3.53854      2.98942
 0.470631     0.382088
 0.935466    -0.00353912
-1.01684     -0.495781
-0.459039    -0.267046
-0.552005    -0.346793
 0.00579625  -0.676987
-0.552005    -0.34186
 2.05107      1.37577
-0.923873    -0.758971
 0.284697     0.889924
 0.284697    -0.838871
-0.830906    -0.654008
-0.552005     0.127372
-0.830906    -0.594799
 2.70184      2.15563
-0.830906    -0.517666
-0.0871707   -0.42109
-0.923873    -0.971152
 0.0987632    0.521618
 0.0987632   -0.351128
 0.284697     0.498347
-0.0871707   -0.0753455
-1.10981     -0.589433
-0.273105     0.239302
-0.923873    -0.810425
-0.0871707    0.210379
-0.459039    -0.249583
 0.19173      0.426465
 0.0987632   -0.0679675
 0.842499     1.21189
-0.459039    -0.386475
-1.10981     -0.672626
 0.842499     0.947789
-0.830906    -0.767555
-0.830906    -0.541281
-0.459039    -0.0258117
 1.30733      0.174127
-1.10981     -0.926231
 0.935466     1.05143
-0.366072    -0.332401
 0.656565    -0.0123439
-0.552005    -0.482579
-0.552005    -0.350549
-0.552005    -0.0328808
-0.0871707    0.239242
-0.273105    -0.399656
 0.19173      0.27318
-0.180138    -0.482925
-1.01684     -0.590579
-0.459039    -0.728664
-0.737939    -0.427332
-1.01684     -0.920821
-0.273105    -0.162545
-0.180138     0.00865365
-0.366072    -0.129993
-1.01684     -0.786483
-1.01684     -0.68516
-0.0871707   -0.487326
-0.0871707   -0.197059
-0.644972    -0.592037
-1.10981     -0.684877
-0.552005    -0.180746
 1.21437      0.913979
 0.284697    -0.561601
 4.34363      3.70139
-1.01684     -0.646015
-0.366072    -0.745207
-0.459039    -0.334022
 2.237        1.5873
-0.737939    -0.521372
 3.07371      3.24355
-0.0871707    0.315718
-0.830906    -0.422003
 0.377664     0.917398
 2.42294      3.30018
-0.830906    -0.936755
-0.366072    -0.124212
-1.01684     -0.724826
-1.01684     -0.738169
-0.0871707   -0.331379
-0.923873    -0.813123
 1.58623      0.235291
 1.21437      0.574868
-0.737939    -0.502223
-0.0871707    0.0798508
 0.284697     0.382482
 0.749532     0.0634729
-0.737939    -0.819756
-0.0871707    0.310966
-0.0871707   -0.724044
-1.10981     -0.798038
-1.01684     -0.395337
-0.737939    -0.0872389
 0.19173     -0.668057
 0.19173      0.578023
-0.644972    -0.877946
 1.1214      -0.152454
-0.830906    -0.229285
 1.30733      1.81756
-0.459039    -0.142953
-0.923873    -0.769795
-0.644972    -0.286825
 0.284697     0.302091
-0.830906    -0.860378
-0.923873    -0.790491
 1.1214       1.7308
 0.00579625   0.133537
-0.0871707   -0.0991156
-0.459039    -0.0590571
-0.830906    -0.51665
-0.923873    -0.959374
-0.830906    -0.743457
-0.923873    -0.543987
-0.830906    -0.494315
 1.1214       0.934967
-0.366072    -0.816135
-0.366072    -0.00883294
-0.830906    -0.747833
 1.02843      0.339297
 0.284697     0.582904
 1.58623      0.911126
-0.180138    -0.57051
 0.377664    -0.416121
 0.00579625  -0.404839
 0.284697     0.171257
-0.644972    -0.857854
-0.644972    -0.264339
-0.180138    -0.116884
 0.377664     0.252046
-0.552005    -0.373289
 0.842499     0.732908
-0.0871707   -0.0197613
 0.0987632   -0.166288
 1.58623      0.629936
 0.470631    -0.508682
-0.737939    -0.204847
-0.552005    -0.506349
 0.656565     0.0248382
-0.737939    -0.453137
-0.366072    -0.736285
-0.180138    -0.095457
-0.552005    -0.437963
 0.0987632    0.150708
-0.923873    -0.641307
 0.470631     0.929767
 0.0987632   -0.114364
-0.644972    -0.461678
-0.459039    -0.289046
 2.88777      1.07885
-0.737939    -0.758884
 0.19173     -0.47018
-0.552005    -0.377521
 1.02843      0.729454
-0.830906    -0.62291
-0.366072    -0.455542
 0.470631     0.561136
 1.30733      1.35109
 0.935466     1.12285
 3.8788       3.40198
 0.284697     0.431583
 3.69287      3.28735
-0.923873    -0.685627
-0.737939    -0.454048
 0.377664     0.857568
 0.470631     3.25603e-05
-1.01684     -0.745204
 2.05107      2.57602
-0.0871707   -0.0252931
-0.0871707   -0.0265558
 0.377664     1.25877
-0.644972    -0.474168
-0.737939    -0.442689
 0.749532     0.853422
-1.01684     -0.671358
-0.644972    -0.657668
 0.470631     0.350588
 2.5159       1.87768
 0.00579625   0.597934
-0.273105     0.665795
-0.830906    -0.776199
-0.830906    -0.401883
-0.644972    -0.620895
-1.01684     -0.691251
-1.10981     -0.783217
-0.273105    -0.147317
-0.830906    -0.455931
 0.377664     0.730491
-0.644972    -0.403012
 0.377664    -0.246993
-0.923873    -0.646345
-1.01684     -0.741693
-0.552005    -0.443078
-0.366072    -0.337369
-0.180138    -0.103016
-1.01684     -0.856387
 3.35261      3.34231
-0.644972    -0.165079
 2.88777      0.426536
 0.749532     0.179578
 1.30733      1.37178
-0.644972    -0.555992
-0.552005    -0.562102
-0.180138    -0.137607
 0.19173     -0.162487
-0.180138     0.251121
 0.935466    -0.128737
-0.366072    -0.391954
 0.377664     0.662048
-0.830906    -0.840167
-1.01684     -0.536823
-0.737939    -0.514171
-0.180138     0.0362041
 0.749532    -0.210443
-0.459039    -0.499259
-1.01684     -0.897846
 0.935466     1.27981
 0.842499    -0.186814
-0.737939    -0.672197
 0.377664     0.178288
 0.377664    -0.110327
-0.180138    -0.158945
-0.0871707    0.0098536
 0.0987632    0.695961
 1.30733      1.54877
-0.366072    -0.562706
-0.366072    -0.485774
-0.552005    -0.159491
-0.644972    -0.69193
-0.923873    -0.515019
-0.273105    -0.0638681
-0.644972    -0.494365
-0.737939    -0.634356
-0.737939    -0.693533
 0.19173     -0.489624
-0.830906    -0.571368
-0.644972    -0.529399
-0.552005    -0.735525
 0.00579625  -0.180531
-0.923873    -0.784867
 0.935466     0.452942
-0.459039    -0.400873
-0.273105    -0.872505
 0.00579625   0.210218
-0.737939    -0.448751
 1.02843      0.060555
-0.552005    -0.586875
 0.935466     1.49871
-1.10981     -0.700461
-0.830906    -0.827567
-0.737939    -0.544065
 2.05107      1.70245
-0.552005    -0.244117
 0.842499     0.51687
-0.923873    -0.921548
-0.366072    -0.507279
 0.0987632   -0.193223
-1.01684     -0.675761
-1.10981      0.192877
 0.284697    -0.661829
 0.00579625  -0.314725
-0.923873    -0.716348
 0.470631     0.642238
-0.644972    -0.424279
 0.00579625  -0.316382
-0.644972    -0.635782
 0.00579625   0.442109
 0.749532     0.539496
-0.459039    -0.190136
-1.10981     -0.894125
-0.923873    -0.446299
-0.180138    -0.490027
 0.470631     1.03852
-0.0871707    0.545449
 1.49327      1.46361
-0.0871707    0.296742
 0.377664     0.469818
-0.830906    -0.63283
 2.70184      1.36519
-0.923873    -0.755808
-0.180138     0.454588
 0.19173      0.55121
-0.552005    -0.359429
-0.923873    -0.731329
 0.377664     0.388799
 0.284697    -0.504584
-0.644972    -0.198722
 0.749532     0.807343
-0.459039    -0.385062

In [ ]:
print(l_reg.intercept_)
print(l_reg.coef_)

[0.0048171]
[[0.87448463]]